config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'main#index'

  resources :product,  only: [:show]

  resources :category, only: [:show]

  resource :cart, only: %i[destroy show] do
   resources :items, only: %i[destroy create]
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items
  belongs_to :user
  
  validates :user_id, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :cart_id, :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :title,       presence: true
  validates :description, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true
  belongs_to :manufacturer
  belongs_to :category

  enum hit: { hit: 1, not_hit: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart, dependent: :destroy

  has_many :authorizations

  validates :email,    presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_cart
  @current_cart ||= begin
      Cart.find_or_create_by(user: current_user)
    end
  end

  def cart_items
   current_cart.cart_items
  end

  def cart_total
    return 0 if cart_items.none?

    cart_items
      .joins(:product)
      .select('(cart_items.quantity * products.price) as total')
      .sum { |x| x[:total] }
  end
  helper_method :current_cart, :cart_items, :cart_total
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def destroy
    current_cart.destroy
    render :show
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include CartsHelper

  def create
    cart_items.create(item_params)
  end

  def destroy
    cart_items.find_by(item_params).destroy
    render :create
  end

  private

  def item_params
    params.permit(:product_id, :quantity)
  end

  helper_method :products
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @manufacturers = Manufacturer.limit(3)
    @products = Product.limit(3)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def products
    @products ||= cart_items.joins(:product).all
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<% unless current_user.nil? %>
  <% if !products.empty? %>
    <div class="table-responsive">
      <table class="table table-hover table-striped">
        <thead>
        <tr>
          <th>Фото</th>
          <th>Наименование</th>
          <th>Кол-во</th>
          <th>Цена</th>
          <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
        </tr>
        </thead>
        <tbody>
        <% qty = [] %>
        <% sum = [] %>
        <% products.map do |item| %>
          <tr>
            <td>
              <% if item.product.img.nil? %>
                <%= link_to(item.product.title, item.product) %>
              <% else %>
                <%= link_to(image_tag(item.product.img), item.product) %>
              <% end %>
            </td>
            <td><%= link_to(item.product.title, item.product) %></td>
            <td>
              <% qty << item.quantity %><%= item.quantity %>шт.
            </td>
            <% pr = item.quantity * item.product.price %>
            <% sum << pr %>
            <td><%= item.product.price %> </td>
            <td>
              <span data-id="<%= item.product_id %>" class="glyphicon glyphicon-remove text-danger del-item" aria-hidden="true"></span>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Итого:</td>
          <td colspan="4" class="text-right cart-qty"><%= qty.sum %> шт.</td>
        </tr>
        <tr>
          <td>На сумму:</td>
          <td colspan="4" class="text-right cart-sum"><%= format("%.2f", sum.sum) %> $</td>
        </tr>

        </tbody>
      </table>
    </div>
  <% else %>
    <h3>Cart is Empty</h3>
  <% end %>
<% else %>
  <span> Please sign in! To view the cart. </span>
  <script>$('#cart .modal-footer a, #cart .modal-footer .btn-danger').css('display', 'none');</script>
<% end %>

app/views/carts/show.html.erb
<%= render 'cart' %>

app/views/items/create.html.erb
<%= render 'carts/cart' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content">
      <%= render 'shared/header' %>
      <%= render 'shared/errors' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/main/_product.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <%= link_to image_tag('drug.png', class: "card-img-top"), product_path(product)%>
    <div class="card-body">
      <h4 class="card-title">
        <%= link_to product.title, product_path(product)%>
      </h4>
      <h5>$<%= product.price %></h5>
      <p class="card-text"><%= product.description %></p>
    </div>
    <div class="card-footer">
    <%=
      link_to 'ADD TO CART',
              cart_items_path,
              remote: true,
              data:      { method: :post , id: product.id },
              class:    "add-cart item_add add-to-cart-link",
              id:       "productAdd"
    %>
    </div>
  </div>
</div>

app/views/main/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-3x">

      <h1 class="my-3">Shop Name</h1>
      <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
      </div>

    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

      <div id="carouselExampleIndicators" class="carousel slide my-4" dataride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"><li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <%= image_tag('dna.jpg', size: '900x350', alt: 'First slide')  %>
          </div>
          <div class="carousel-item">
            <%= image_tag('world.png', size: '900x350', alt: 'First slide') %>
          </div>
          <div class="carousel-item">
            <%= image_tag('virus.jpg', size: '900x350', alt: 'First slide') %>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

      <div class="row">
       <%= render partial: "product", collection: @products %>
      </div>

    </div>
    <!-- /.col-lg-9 -->

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->

app/views/product/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h3>
				<%= @product.title %>
			</h3>
      <%= image_tag('drug.png', class: "rounded", size: '250x250')  %>
			<table class="table table-striped table-hover table-sm">
				<thead>
					<tr>
						<th>
							Description
						</th>
						<th>
							Status
						</th>
						<th>
							Price
						</th>
            <th>
							Manufacturer
						</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<%= @product.description %>
						</td>
						<td>
							<%= @product.status %>
						</td>
						<td>
							$<%= @product.price %>
						</td>
            <td>
							<%= @product.manufacturer.title %>
						</td>
					</tr>
					</tbody>
			</table>
		</div>
	</div>
</div>

app/views/products/_product.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <%= link_to image_tag('drug.png', class: "card-img-top"), '#'%>
    <div class="card-body">
      <h4 class="card-title">
        <%= link_to product.title, '#'%>
      </h4>
      <h5>$<%= product.price %></h5>
      <p class="card-text"><%= product.description %></p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Order</small>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  

app/views/shared/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :destroy,  class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Cart', cart_path, class: "nav-link" %>
        </li>

      </ul>
    </div>
  </div>
</nav>